checkpoint working on todeCommand and gsDevKitCommand

diff --git a/bin/todeCommand b/bin/todeCommand
--- a/bin/todeCommand
+++ b/bin/todeCommand
@@ -23,6 +23,13 @@ EXAMPLES
 HELP
 }
 
+set -e # exit on error
+if [ "${GS_HOME}x" = "x" ] ; then
+  echo "the GS_HOME environment variable needs to be defined"
+  exit 1
+fi
+source ${GS_HOME}/bin/defGsDevKit.env
+
 case "$1" in
   --*) # pass to tode
     ;;
@@ -37,17 +44,11 @@ case "$1" in
     ;;
 esac
 
-if [ "${GS_HOME}x" = "x" ] ; then
-  echo "the GS_HOME environment variable needs to be defined"
-  exit 1
-fi
-
-#set -e # exit on error
-pharo=$GS_HOME/pharo
-
-if [ ! -e $pharo/todeClient.image ] ; then
-  $GS_HOME/bin/createTodeImage
+if [ ! -e ${GS_GS_SERVER_PHARO}/todeCommand.image ] ; then
+  $GS_GS_SERVER/bin/create_gs_server_image -d $GS_GS_SERVER_PHARO todeCommand
 fi
 
 # Run script
-$pharo/pharo $pharo/todeClient.image $*
+${GS_GS_SERVER_PHARO}/pharo ${GS_GS_SERVER_PHARO}/tode.image $*
+
+echo "...finished $(basename $0)"
