start and stop scripts should exit on error

diff --git a/bin/gs/stopGemstone b/bin/gs/stopGemstone
--- a/bin/gs/stopGemstone
+++ b/bin/gs/stopGemstone
@@ -7,6 +7,8 @@ echo "================="
 echo "   GsDevKit GemStone script: $(basename $0) $*"
 echo "================="
 
+set -e # exit on error
+
 if [ -s $GEMSTONE/seaside/etc/gemstone.secret ]; then
       . $GEMSTONE/seaside/etc/gemstone.secret
 else
